apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  APP_ENV: "production"
  MAX_DB_CONNECTIONS: "10"
  MAX_REDIS_CONNECTIONS: "10"
  RUST_LOG: "info"
