apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: true-label-sit

resources:
  - ../../base

images:
  - name: tarunvishwakarma/true-lable-backend
    newTag: sit
  - name: tarunvishwakarma/true-lable-web
    newTag: sit

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: ConfigMap
      name: backend-config
    patch: |
      - op: replace
        path: /data/APP_ENV
        value: sit
