[package]
name = "truelabel-backend"
version = "0.0.1"
edition = "2024"
description = "TrueLabel - Open-source barcode scanner with crowdsourced nutrition database"
repository = "https://github.com/TarunVishwakarma1/true-lable"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.104"
dotenvy = "0.15.7"
redis = { version = "1", features = ["tokio-comp"] }
tokio = { version = "1.53.1", features = ["full"] }
tokio-postgres = "0.7.18"
