apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@db-service:5432/postgres"
  REDIS_URL: "redis://redis-service:6379"
  APP_ENV: "docker"
