apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: true-label-dev

resources:
  - ../../base

images:
  - name: tarunvishwakarma/true-lable-backend
    newTag: dev
  - name: tarunvishwakarma/true-lable-web
    newTag: dev
  - name: tarunvishwakarma/true-lable-dashboard
    newTag: dev
  - name: tarunvishwakarma/true-lable-docs
    newTag: dev

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: dashboard
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: docs
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: backend
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
  - target:
      kind: HorizontalPodAutoscaler
      name: web
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
  - target:
      kind: HorizontalPodAutoscaler
      name: dashboard
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
  - target:
      kind: HorizontalPodAutoscaler
      name: docs
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
  - target:
      kind: ConfigMap
      name: backend-config
    patch: |
      - op: replace
        path: /data/APP_ENV
        value: development
